name: Auto-assign issue author
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author as assignee
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue edit "${{ github.event.issue.number }}" --add-assignee "${{ github.event.issue.user.login }}" --repo "${{ github.repository }}"
